# Older people projected prevalence

The analysis below attempts to replicate the methodology used by poppi to provide population projections

In [2]:
import dotenv
import os
import fsspec
import requests
import polars as pl
import polars.selectors as cs
from pathlib import Path
from zipfile import ZipFile
import plotly.express as px
from io import BytesIO

# set the OUTPUT_DIRECTORY using an environment variable, a .env file or leave it as the current directory
dotenv.load_dotenv()
OUTPUT_DIRECTORY = Path(os.environ.get("OUTPUT_DIRECTORY", "."))

# Population Projections

I have used the 2022 based migration category variant dataset for estimating population at District level

This is in line with ONS guidance and projects populations in line with the most likely migration levels

In [3]:
response = requests.get(
    "https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/populationandmigration/populationprojections/datasets/"
    "localauthoritiesinenglandz1/2022basedmigrationcategoryvariant/2022snpppopulationsyoamigcat.zip"
)
with ZipFile(BytesIO(response.content)) as zf:
    with zf.open("2022 SNPP Population persons.csv") as file:
        population_projections = pl.read_csv(file)
population_projections

shape: (28_428, 31)
┌───────────┬────────────┬───────────┬─────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ AREA_CODE ┆ AREA_NAME  ┆ COMPONENT ┆ SEX     ┆ … ┆ 2044      ┆ 2045      ┆ 2046      ┆ 2047      │
│ ---       ┆ ---        ┆ ---       ┆ ---     ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str       ┆ str        ┆ str       ┆ str     ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪════════════╪═══════════╪═════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ E06000047 ┆ County     ┆ Populatio ┆ persons ┆ … ┆ 4691.745  ┆ 4677.61   ┆ 4660.477  ┆ 4641.389  │
│           ┆ Durham     ┆ n         ┆         ┆   ┆           ┆           ┆           ┆           │
│ E06000047 ┆ County     ┆ Populatio ┆ persons ┆ … ┆ 4729.662  ┆ 4719.802  ┆ 4706.172  ┆ 4689.456  │
│           ┆ Durham     ┆ n         ┆         ┆   ┆           ┆           ┆           ┆           │
│ E06000047 ┆ County     ┆ Populatio ┆ persons ┆ … ┆ 4809.067  ┆ 4805.534  ┆ 4795.99   ┆ 4782.625  │
│           ┆ Durham     ┆ n         ┆         ┆   ┆           ┆           ┆           ┆           │
│ E06000047 ┆ County     ┆ Populatio ┆ persons ┆ … ┆ 4848.588  ┆ 4850.858  ┆ 4847.737  ┆ 4838.532  │
│           ┆ Durham     ┆ n         ┆         ┆   ┆           ┆           ┆           ┆           │
│ E06000047 ┆ County     ┆ Populatio ┆ persons ┆ … ┆ 4884.307  ┆ 4889.729  ┆ 4892.419  ┆ 4889.667  │
│           ┆ Durham     ┆ n         ┆         ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …          ┆ …         ┆ …       ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ E07000189 ┆ South      ┆ Populatio ┆ persons ┆ … ┆ 1361.155  ┆ 1423.155  ┆ 1490.696  ┆ 1536.651  │
│           ┆ Somerset   ┆ n         ┆         ┆   ┆           ┆           ┆           ┆           │
│ E07000189 ┆ South      ┆ Populatio ┆ persons ┆ … ┆ 1177.527  ┆ 1247.846  ┆ 1305.933  ┆ 1368.545  │
│           ┆ Somerset   ┆ n         ┆         ┆   ┆           ┆           ┆           ┆           │
│ E07000189 ┆ South      ┆ Populatio ┆ persons ┆ … ┆ 1063.233  ┆ 1082.142  ┆ 1148.334  ┆ 1202.798  │
│           ┆ Somerset   ┆ n         ┆         ┆   ┆           ┆           ┆           ┆           │
│ E07000189 ┆ South      ┆ Populatio ┆ persons ┆ … ┆ 5019.982  ┆ 5058.768  ┆ 5113.671  ┆ 5224.696  │
│           ┆ Somerset   ┆ n         ┆         ┆   ┆           ┆           ┆           ┆           │
│ E07000189 ┆ South      ┆ Populatio ┆ persons ┆ … ┆ 194519.93 ┆ 195277.78 ┆ 196028.34 ┆ 196769.36 │
│           ┆ Somerset   ┆ n         ┆         ┆   ┆ 6         ┆ 2         ┆ 3         ┆ 7         │
└───────────┴────────────┴───────────┴─────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
SURREY_EAST = (
    "E07000207",  # "Elmbridge",
    "E07000208",  # "Epsom and Ewell",
    "E07000210",  # "Mole Valley",
    "E07000211",  # "Reigate and Banstead",
    "E07000215",  # "Tandridge",
)
SURREY_WEST = (
    "E07000209",  # "Guildford",
    "E07000212",  # "Runnymede",
    "E07000213",  # "Spelthorne",
    "E07000214",  # "Surrey Heath",
    "E07000216",  # "Waverley",
    "E07000217",  # "Woking",
)

lgr_mapping = population_projections.select(
    "AREA_CODE", 
    "AREA_NAME",
    LGR_ALLOCATION=pl.when(pl.col("AREA_CODE").is_in(SURREY_EAST))
    .then(pl.lit("EAST"))
    .when(pl.col("AREA_CODE").is_in(SURREY_WEST))
    .then(pl.lit("WEST"))
).filter(pl.col("LGR_ALLOCATION").is_not_null()).unique()
lgr_mapping

shape: (11, 3)
┌───────────┬──────────────────────┬────────────────┐
│ AREA_CODE ┆ AREA_NAME            ┆ LGR_ALLOCATION │
│ ---       ┆ ---                  ┆ ---            │
│ str       ┆ str                  ┆ str            │
╞═══════════╪══════════════════════╪════════════════╡
│ E07000213 ┆ Spelthorne           ┆ WEST           │
│ E07000212 ┆ Runnymede            ┆ WEST           │
│ E07000209 ┆ Guildford            ┆ WEST           │
│ E07000210 ┆ Mole Valley          ┆ EAST           │
│ E07000208 ┆ Epsom and Ewell      ┆ EAST           │
│ …         ┆ …                    ┆ …              │
│ E07000211 ┆ Reigate and Banstead ┆ EAST           │
│ E07000217 ┆ Woking               ┆ WEST           │
│ E07000214 ┆ Surrey Heath         ┆ WEST           │
│ E07000215 ┆ Tandridge            ┆ EAST           │
│ E07000216 ┆ Waverley             ┆ WEST           │
└───────────┴──────────────────────┴────────────────┘

In [5]:
older_population = population_projections.with_columns(
    pl.col("AGE_GROUP").str.extract(r"\d+", 0).cast(pl.Int32)
).join(
    lgr_mapping,
    on=["AREA_CODE", "AREA_NAME"]
).filter(
    pl.col("AGE_GROUP") >= 65
)
older_population

shape: (286, 32)
┌───────────┬───────────┬────────────┬─────────┬───┬──────────┬──────────┬──────────┬──────────────┐
│ AREA_CODE ┆ AREA_NAME ┆ COMPONENT  ┆ SEX     ┆ … ┆ 2045     ┆ 2046     ┆ 2047     ┆ LGR_ALLOCATI │
│ ---       ┆ ---       ┆ ---        ┆ ---     ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ON           │
│ str       ┆ str       ┆ str        ┆ str     ┆   ┆ f64      ┆ f64      ┆ f64      ┆ ---          │
│           ┆           ┆            ┆         ┆   ┆          ┆          ┆          ┆ str          │
╞═══════════╪═══════════╪════════════╪═════════╪═══╪══════════╪══════════╪══════════╪══════════════╡
│ E07000207 ┆ Elmbridge ┆ Population ┆ persons ┆ … ┆ 1835.478 ┆ 1750.418 ┆ 1758.979 ┆ EAST         │
│ E07000207 ┆ Elmbridge ┆ Population ┆ persons ┆ … ┆ 1741.673 ┆ 1801.854 ┆ 1720.328 ┆ EAST         │
│ E07000207 ┆ Elmbridge ┆ Population ┆ persons ┆ … ┆ 1657.773 ┆ 1710.677 ┆ 1770.336 ┆ EAST         │
│ E07000207 ┆ Elmbridge ┆ Population ┆ persons ┆ … ┆ 1622.616 ┆ 1634.446 ┆ 1687.345 ┆ EAST         │
│ E07000207 ┆ Elmbridge ┆ Population ┆ persons ┆ … ┆ 1591.09  ┆ 1602.838 ┆ 1614.683 ┆ EAST         │
│ …         ┆ …         ┆ …          ┆ …       ┆ … ┆ …        ┆ …        ┆ …        ┆ …            │
│ E07000217 ┆ Woking    ┆ Population ┆ persons ┆ … ┆ 566.229  ┆ 592.175  ┆ 601.778  ┆ WEST         │
│ E07000217 ┆ Woking    ┆ Population ┆ persons ┆ … ┆ 545.433  ┆ 538.829  ┆ 563.427  ┆ WEST         │
│ E07000217 ┆ Woking    ┆ Population ┆ persons ┆ … ┆ 487.01   ┆ 510.946  ┆ 506.366  ┆ WEST         │
│ E07000217 ┆ Woking    ┆ Population ┆ persons ┆ … ┆ 419.279  ┆ 447.692  ┆ 469.875  ┆ WEST         │
│ E07000217 ┆ Woking    ┆ Population ┆ persons ┆ … ┆ 2039.376 ┆ 2061.309 ┆ 2107.21  ┆ WEST         │
└───────────┴───────────┴────────────┴─────────┴───┴──────────┴──────────┴──────────┴──────────────┘

# Indicator 1 - Dementia
I chose to sourc

In [6]:
dementia = pl.read_csv("https://fingertips.phe.org.uk/api/all_data/csv/for_one_indicator?indicator_id=92949").filter(
    pl.col("Area Code").is_in(SURREY_EAST + SURREY_WEST),
)
dementia

shape: (99, 27)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬──────────┬───────────┬────────┐
│ Indicator  ┆ Indicator  ┆ Parent     ┆ Parent    ┆ … ┆ Time      ┆ New data ┆ Compared  ┆ Time   │
│ ID         ┆ Name       ┆ Code       ┆ Name      ┆   ┆ period    ┆ ---      ┆ to goal   ┆ period │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ Sortable  ┆ str      ┆ ---       ┆ range  │
│ i64        ┆ str        ┆ str        ┆ str       ┆   ┆ ---       ┆          ┆ str       ┆ ---    │
│            ┆            ┆            ┆           ┆   ┆ i64       ┆          ┆           ┆ str    │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪════════╡
│ 92949      ┆ Estimated  ┆ E92000001  ┆ England   ┆ … ┆ 20170000  ┆ null     ┆ Amber     ┆ 1y     │
│            ┆ dementia   ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ diagnosis  ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ r…         ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│ 92949      ┆ Estimated  ┆ E92000001  ┆ England   ┆ … ┆ 20170000  ┆ null     ┆ Red       ┆ 1y     │
│            ┆ dementia   ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ diagnosis  ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ r…         ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│ 92949      ┆ Estimated  ┆ E92000001  ┆ England   ┆ … ┆ 20170000  ┆ null     ┆ Amber     ┆ 1y     │
│            ┆ dementia   ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ diagnosis  ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ r…         ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│ 92949      ┆ Estimated  ┆ E92000001  ┆ England   ┆ … ┆ 20170000  ┆ null     ┆ Amber     ┆ 1y     │
│            ┆ dementia   ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ diagnosis  ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ r…         ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│ 92949      ┆ Estimated  ┆ E92000001  ┆ England   ┆ … ┆ 20170000  ┆ null     ┆ Amber     ┆ 1y     │
│            ┆ dementia   ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ diagnosis  ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ r…         ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …      │
│ 92949      ┆ Estimated  ┆ E92000001  ┆ England   ┆ … ┆ 20250000  ┆ null     ┆ Amber     ┆ 1y     │
│            ┆ dementia   ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ diagnosis  ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ r…         ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│ 92949      ┆ Estimated  ┆ E92000001  ┆ England   ┆ … ┆ 20250000  ┆ null     ┆ Amber     ┆ 1y     │
│            ┆ dementia   ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ diagnosis  ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ r…         ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│ 92949      ┆ Estimated  ┆ E92000001  ┆ England   ┆ … ┆ 20250000  ┆ null     ┆ Amber     ┆ 1y     │
│            ┆ dementia   ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ diagnosis  ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ r…         ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│ 92949      ┆ Estimated  ┆ E92000001  ┆ England   ┆ … ┆ 20250000  ┆ null     ┆ Amber     ┆ 1y     │
│            ┆ dementia   ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ diagnosis  ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ r…         ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│ 92949      ┆ Estimated  ┆ E92000001  ┆ England   ┆ … ┆ 20250000  ┆ null     ┆ Green     ┆ 1y     │
│            ┆ dementia   ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ diagnosis  ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
│            ┆ r…         ┆            ┆           ┆   ┆           ┆          ┆           ┆        │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴──────────┴───────────┴────────┘

In [7]:
years_to_check = dementia["Time period"].unique().cast(pl.String).to_list()
older_population.group_by(
    "AREA_CODE", "AREA_NAME"
).agg(
    cs.by_name(years_to_check, require_all=False).sum()
)

shape: (11, 6)
┌───────────┬─────────────────┬─────────┬───────────┬───────────┬───────────┐
│ AREA_CODE ┆ AREA_NAME       ┆ 2022    ┆ 2023      ┆ 2024      ┆ 2025      │
│ ---       ┆ ---             ┆ ---     ┆ ---       ┆ ---       ┆ ---       │
│ str       ┆ str             ┆ f64     ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═════════════════╪═════════╪═══════════╪═══════════╪═══════════╡
│ E07000216 ┆ Waverley        ┆ 28757.0 ┆ 29235.599 ┆ 29800.165 ┆ 30341.595 │
│ E07000213 ┆ Spelthorne      ┆ 18666.0 ┆ 18768.044 ┆ 18974.214 ┆ 19138.92  │
│ E07000207 ┆ Elmbridge       ┆ 25357.0 ┆ 25730.187 ┆ 26170.144 ┆ 26640.989 │
│ E07000217 ┆ Woking          ┆ 17592.0 ┆ 17847.576 ┆ 18054.206 ┆ 18303.44  │
│ E07000209 ┆ Guildford       ┆ 25577.0 ┆ 25888.657 ┆ 26245.866 ┆ 26614.089 │
│ …         ┆ …               ┆ …       ┆ …         ┆ …         ┆ …         │
│ E07000210 ┆ Mole Valley     ┆ 21237.0 ┆ 21480.702 ┆ 21832.47  ┆ 22171.527 │
│ E07000212 ┆ Runnymede       ┆ 15333.0 ┆ 15524.244 ┆ 15786.168 ┆ 16045.548 │
│ E07000215 ┆ Tandridge       ┆ 18722.0 ┆ 18943.853 ┆ 19218.085 ┆ 19486.364 │
│ E07000214 ┆ Surrey Heath    ┆ 18377.0 ┆ 18671.033 ┆ 18954.801 ┆ 19207.879 │
│ E07000208 ┆ Epsom and Ewell ┆ 14847.0 ┆ 14949.654 ┆ 15082.212 ┆ 15258.447 │
└───────────┴─────────────────┴─────────┴───────────┴───────────┴───────────┘

In [14]:
dementia_pop_by_year = older_population.group_by(
    "AREA_CODE", "AREA_NAME", "LGR_ALLOCATION"
).agg(
    cs.by_name(years_to_check, require_all=False).sum()
).unpivot(
    cs.by_name(years_to_check, require_all=False),
    index=["AREA_CODE", "AREA_NAME", "LGR_ALLOCATION"],
    variable_name="year",
    value_name="estimated_population"
).with_columns(
    pl.col("year")
)
dementia_pop_by_year

shape: (44, 5)
┌───────────┬──────────────────────┬────────────────┬──────┬──────────────────────┐
│ AREA_CODE ┆ AREA_NAME            ┆ LGR_ALLOCATION ┆ year ┆ estimated_population │
│ ---       ┆ ---                  ┆ ---            ┆ ---  ┆ ---                  │
│ str       ┆ str                  ┆ str            ┆ str  ┆ f64                  │
╞═══════════╪══════════════════════╪════════════════╪══════╪══════════════════════╡
│ E07000215 ┆ Tandridge            ┆ EAST           ┆ 2022 ┆ 18722.0              │
│ E07000213 ┆ Spelthorne           ┆ WEST           ┆ 2022 ┆ 18666.0              │
│ E07000208 ┆ Epsom and Ewell      ┆ EAST           ┆ 2022 ┆ 14847.0              │
│ E07000212 ┆ Runnymede            ┆ WEST           ┆ 2022 ┆ 15333.0              │
│ E07000214 ┆ Surrey Heath         ┆ WEST           ┆ 2022 ┆ 18377.0              │
│ …         ┆ …                    ┆ …              ┆ …    ┆ …                    │
│ E07000216 ┆ Waverley             ┆ WEST           ┆ 2025 ┆ 30341.595            │
│ E07000207 ┆ Elmbridge            ┆ EAST           ┆ 2025 ┆ 26640.989            │
│ E07000210 ┆ Mole Valley          ┆ EAST           ┆ 2025 ┆ 22171.527            │
│ E07000211 ┆ Reigate and Banstead ┆ EAST           ┆ 2025 ┆ 29017.832            │
│ E07000209 ┆ Guildford            ┆ WEST           ┆ 2025 ┆ 26614.089            │
└───────────┴──────────────────────┴────────────────┴──────┴──────────────────────┘

In [15]:
dementia_vis = dementia.select(
    AREA_CODE="Area Code",
    estimated_count="Denominator",
    year=pl.col("Time period").cast(pl.String)
).join(
    dementia_pop_by_year,
    on=["AREA_CODE", "year"]
).with_columns(
    estimated_prevalence=(pl.col("estimated_count") / pl.col("estimated_population")).round(3) * 100
)
dementia_vis

shape: (44, 7)
┌───────────┬───────────────┬──────┬───────────────┬───────────────┬───────────────┬───────────────┐
│ AREA_CODE ┆ estimated_cou ┆ year ┆ AREA_NAME     ┆ LGR_ALLOCATIO ┆ estimated_pop ┆ estimated_pre │
│ ---       ┆ nt            ┆ ---  ┆ ---           ┆ N             ┆ ulation       ┆ valence       │
│ str       ┆ ---           ┆ str  ┆ str           ┆ ---           ┆ ---           ┆ ---           │
│           ┆ f64           ┆      ┆               ┆ str           ┆ f64           ┆ f64           │
╞═══════════╪═══════════════╪══════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╡
│ E07000207 ┆ 1874.6        ┆ 2022 ┆ Elmbridge     ┆ EAST          ┆ 25357.0       ┆ 7.4           │
│ E07000208 ┆ 1050.4        ┆ 2022 ┆ Epsom and     ┆ EAST          ┆ 14847.0       ┆ 7.1           │
│           ┆               ┆      ┆ Ewell         ┆               ┆               ┆               │
│ E07000209 ┆ 1388.5        ┆ 2022 ┆ Guildford     ┆ WEST          ┆ 25577.0       ┆ 5.4           │
│ E07000210 ┆ 1528.5        ┆ 2022 ┆ Mole Valley   ┆ EAST          ┆ 21237.0       ┆ 7.2           │
│ E07000211 ┆ 1851.2        ┆ 2022 ┆ Reigate and   ┆ EAST          ┆ 27529.0       ┆ 6.7           │
│           ┆               ┆      ┆ Banstead      ┆               ┆               ┆               │
│ …         ┆ …             ┆ …    ┆ …             ┆ …             ┆ …             ┆ …             │
│ E07000213 ┆ 1369.5        ┆ 2025 ┆ Spelthorne    ┆ WEST          ┆ 19138.92      ┆ 7.2           │
│ E07000214 ┆ 1569.8        ┆ 2025 ┆ Surrey Heath  ┆ WEST          ┆ 19207.879     ┆ 8.2           │
│ E07000215 ┆ 1513.1        ┆ 2025 ┆ Tandridge     ┆ EAST          ┆ 19486.364     ┆ 7.8           │
│ E07000216 ┆ 2571.6        ┆ 2025 ┆ Waverley      ┆ WEST          ┆ 30341.595     ┆ 8.5           │
│ E07000217 ┆ 1457.4        ┆ 2025 ┆ Woking        ┆ WEST          ┆ 18303.44      ┆ 8.0           │
└───────────┴───────────────┴──────┴───────────────┴───────────────┴───────────────┴───────────────┘

In [16]:
fig = px.line(
    dementia_vis,
    x="year",
    y="estimated_prevalence",
    color="AREA_NAME"
)
# brief analysis of the time series below doesn't give enough evidence to suggest prevalence changes significantly enough to warant a more rigorous approach
# a drop in reigate and banstead and increase in tandridge look to me like a change in methodology / allocation
# given it's nhs data, it's likely the estimates are based on gp registrations and this could suggest a gp that was previously allocated to reigate is now allocated to tandridge
# given reigate and tandridge are neighboring I think this is the simplest explanation

# as a result, I'll just use the latest prevalence estimate as planned
fig.show()

In [17]:
dementia_projections = older_population.group_by(
    "AREA_CODE", "AREA_NAME", "LGR_ALLOCATION"
).agg(
    projected_population_2025=pl.sum("2025"),
    projected_population_2040=pl.sum("2040")
)
dementia_projections

shape: (11, 5)
┌───────────┬──────────────────────┬────────────────┬───────────────────────┬──────────────────────┐
│ AREA_CODE ┆ AREA_NAME            ┆ LGR_ALLOCATION ┆ projected_population_ ┆ projected_population │
│ ---       ┆ ---                  ┆ ---            ┆ 2025                  ┆ _2040                │
│ str       ┆ str                  ┆ str            ┆ ---                   ┆ ---                  │
│           ┆                      ┆                ┆ f64                   ┆ f64                  │
╞═══════════╪══════════════════════╪════════════════╪═══════════════════════╪══════════════════════╡
│ E07000217 ┆ Woking               ┆ WEST           ┆ 18303.44              ┆ 22000.482            │
│ E07000213 ┆ Spelthorne           ┆ WEST           ┆ 19138.92              ┆ 22975.208            │
│ E07000209 ┆ Guildford            ┆ WEST           ┆ 26614.089             ┆ 32829.135            │
│ E07000212 ┆ Runnymede            ┆ WEST           ┆ 16045.548             ┆ 19951.584            │
│ E07000215 ┆ Tandridge            ┆ EAST           ┆ 19486.364             ┆ 23845.341            │
│ …         ┆ …                    ┆ …              ┆ …                     ┆ …                    │
│ E07000210 ┆ Mole Valley          ┆ EAST           ┆ 22171.527             ┆ 27576.316            │
│ E07000207 ┆ Elmbridge            ┆ EAST           ┆ 26640.989             ┆ 34625.482            │
│ E07000211 ┆ Reigate and Banstead ┆ EAST           ┆ 29017.832             ┆ 36989.192            │
│ E07000208 ┆ Epsom and Ewell      ┆ EAST           ┆ 15258.447             ┆ 17981.524            │
│ E07000214 ┆ Surrey Heath         ┆ WEST           ┆ 19207.879             ┆ 23945.725            │
└───────────┴──────────────────────┴────────────────┴───────────────────────┴──────────────────────┘

In [12]:
calculated_prevalence_in_older_people=pl.col("estimated_count_2025") / pl.col("projected_population_2025")

dementia_district = dementia.filter(
    # extract latest estimates for 2025 only
    pl.col("Time period") == 2025
).select(
    AREA_CODE="Area Code",
    diagnosed_count_2025="Count",
    estimated_count_2025="Denominator"
).join(
    dementia_projections, on="AREA_CODE"
).select(
    "AREA_CODE",
    "AREA_NAME",
    "LGR_ALLOCATION",
    count="estimated_count_2025",
    reference_year=pl.lit(2025),
    prevalence_estimate=(calculated_prevalence_in_older_people * 100).round(1),
    estimated_count_2025="estimated_count_2025",
    projected_population_2025="projected_population_2025",
    projected_population_2040="projected_population_2040",
    projected_count_2040=pl.col("projected_population_2040") * calculated_prevalence_in_older_people
)
dementia_district

shape: (11, 10)
┌───────────┬────────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ AREA_CODE ┆ AREA_NAME  ┆ LGR_ALLOCA ┆ count  ┆ … ┆ estimated ┆ projected ┆ projected ┆ projected │
│ ---       ┆ ---        ┆ TION       ┆ ---    ┆   ┆ _count_20 ┆ _populati ┆ _populati ┆ _count_20 │
│ str       ┆ str        ┆ ---        ┆ f64    ┆   ┆ 25        ┆ on_2025   ┆ on_2040   ┆ 40        │
│           ┆            ┆ str        ┆        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆            ┆            ┆        ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪════════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ E07000213 ┆ Spelthorne ┆ WEST       ┆ 1369.5 ┆ … ┆ 1369.5    ┆ 19138.92  ┆ 22975.208 ┆ 1644.0085 │
│           ┆            ┆            ┆        ┆   ┆           ┆           ┆           ┆ 1         │
│ E07000212 ┆ Runnymede  ┆ WEST       ┆ 1061.8 ┆ … ┆ 1061.8    ┆ 16045.548 ┆ 19951.584 ┆ 1320.2784 │
│           ┆            ┆            ┆        ┆   ┆           ┆           ┆           ┆ 9         │
│ E07000209 ┆ Guildford  ┆ WEST       ┆ 1498.6 ┆ … ┆ 1498.6    ┆ 26614.089 ┆ 32829.135 ┆ 1848.5600 │
│           ┆            ┆            ┆        ┆   ┆           ┆           ┆           ┆ 51        │
│ E07000210 ┆ Mole       ┆ EAST       ┆ 1622.4 ┆ … ┆ 1622.4    ┆ 22171.527 ┆ 27576.316 ┆ 2017.8950 │
│           ┆ Valley     ┆            ┆        ┆   ┆           ┆           ┆           ┆ 72        │
│ E07000208 ┆ Epsom and  ┆ EAST       ┆ 1090.0 ┆ … ┆ 1090.0    ┆ 15258.447 ┆ 17981.524 ┆ 1284.5252 │
│           ┆ Ewell      ┆            ┆        ┆   ┆           ┆           ┆           ┆ 97        │
│ …         ┆ …          ┆ …          ┆ …      ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ E07000211 ┆ Reigate    ┆ EAST       ┆ 1758.0 ┆ … ┆ 1758.0    ┆ 29017.832 ┆ 36989.192 ┆ 2240.9323 │
│           ┆ and        ┆            ┆        ┆   ┆           ┆           ┆           ┆ 87        │
│           ┆ Banstead   ┆            ┆        ┆   ┆           ┆           ┆           ┆           │
│ E07000217 ┆ Woking     ┆ WEST       ┆ 1457.4 ┆ … ┆ 1457.4    ┆ 18303.44  ┆ 22000.482 ┆ 1751.7746 │
│           ┆            ┆            ┆        ┆   ┆           ┆           ┆           ┆ 65        │
│ E07000214 ┆ Surrey     ┆ WEST       ┆ 1569.8 ┆ … ┆ 1569.8    ┆ 19207.879 ┆ 23945.725 ┆ 1957.0093 │
│           ┆ Heath      ┆            ┆        ┆   ┆           ┆           ┆           ┆ 66        │
│ E07000215 ┆ Tandridge  ┆ EAST       ┆ 1513.1 ┆ … ┆ 1513.1    ┆ 19486.364 ┆ 23845.341 ┆ 1851.5709 │
│           ┆            ┆            ┆        ┆   ┆           ┆           ┆           ┆ 48        │
│ E07000216 ┆ Waverley   ┆ WEST       ┆ 2571.6 ┆ … ┆ 2571.6    ┆ 30341.595 ┆ 38785.505 ┆ 3287.2630 │
│           ┆            ┆            ┆        ┆   ┆           ┆           ┆           ┆ 68        │
└───────────┴────────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [51]:
def as_expr(val) -> pl.Expr:
    if isinstance(val, pl.Expr):
        return val
    if isinstance(val, str):
        return pl.col(val)
    return pl.lit(val)

def round_to_int(value, nearest: int = 1) -> pl.Expr:
    return (
        (as_expr(value) / nearest).round(mode="half_away_from_zero").cast(pl.Int32) * nearest
    )

def as_percent(numerator, denominator, decimals: int=1) -> pl.Expr:
    return (as_expr(numerator) / as_expr(denominator) * 100).round(decimals, mode="half_away_from_zero")

In [52]:
estimated_prevalence = pl.col("projected_count_2040") / pl.col("projected_population_2040")

dementia_counts = dementia_district.group_by(
    "LGR_ALLOCATION",
).agg(
    round_to_int(
        pl.sum("estimated_count_2025", "projected_population_2025", "projected_population_2040", "projected_count_2040"),
        100
    ),
).with_columns(
    estimated_increase=pl.col("projected_count_2040") - pl.col("estimated_count_2025")
)
dementia_counts

shape: (2, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ LGR_ALLOCATION ┆ estimated_coun ┆ projected_popu ┆ projected_pop ┆ projected_cou ┆ estimated_inc │
│ ---            ┆ t_2025         ┆ lation_2025    ┆ ulation_2040  ┆ nt_2040       ┆ rease         │
│ str            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│                ┆ i32            ┆ i32            ┆ i32           ┆ i32           ┆ i32           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ WEST           ┆ 9500           ┆ 129700         ┆ 160500        ┆ 11800         ┆ 2300          │
│ EAST           ┆ 8000           ┆ 112600         ┆ 141000        ┆ 10000         ┆ 2000          │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

# Sanity check
- Population of over 65's in EAST is expected to increase by just under 30000
- a prevalence of between 5 and 10 percent is somewhere between 1 in 10 and 1 in 20. Let's say 1 in 15.
- 1/15 == 2/30 == 2000/30000
- the count of people affected is expected to increase by 2000 

consider these results to have a very generous margin for error as:
- they don't account for different migration scenarios
- they barely account for projected life expectancy
- they don't account for changes in prevalence
- they barely account for age stratification (age band is 65 and over)

# Frailty indicator

A reasonable indication of frailty at local authority level appears to be the number of emergency hospital admissions for falls.